import TableGeneration.Policy
import TableGeneration.Policies.Accepted.P82eaf805f71c

namespace TableGeneration

open Operations

/- This file is generated by scripts/promote.py. -/

def bestKnownGeneratedPoints (mode : ProductMode) (k : Nat) : List Point :=
  if mode = .PhaseTripleProduct ∧ k = 4 then
    Policies.Accepted.P82eaf805f71c.implementation.generatedPoints
      mode k
  else
    baselineGeneratedPoints mode k

def bestKnownGeneratePointsInOrder
    (mode : ProductMode) (k : Nat) (hk : k >= 2) : List Point :=
  if mode = .PhaseTripleProduct ∧ k = 4 then
    Policies.Accepted.P82eaf805f71c.implementation.generatePointsInOrder
      mode k hk
  else
    baselineGeneratePointsInOrder mode k hk

def bestKnownGenerate
    (mode : ProductMode) (k : Nat) (hk : k >= 2) : Prog k :=
  if mode = .PhaseTripleProduct ∧ k = 4 then
    Policies.Accepted.P82eaf805f71c.implementation.generate
      mode k hk
  else
    baselineGenerate mode k hk

def bestKnownPolicyId (mode : ProductMode) (k : Nat) : String :=
  if mode = .PhaseTripleProduct ∧ k = 4 then
    "82eaf805f71cc6a0dd8154007729d14b9f63d601"
  else
    "general"

end TableGeneration
