import TableGeneration.Policy
import TableGeneration.Policies.Accepted.P52ec6fce9b57
import TableGeneration.Policies.Accepted.P6f7d25984ff8
import TableGeneration.Policies.Accepted.Pf4aff955f16b

namespace TableGeneration

open Operations

/- This file is generated by scripts/promote.py. -/

def bestKnownGeneratedPoints (mode : ProductMode) (k : Nat) : List Point :=
  if mode = .PhaseProduct ∧ k = 2 then
    Policies.Accepted.P6f7d25984ff8.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 2 then
    Policies.Accepted.P52ec6fce9b57.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 3 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 3 then
    Policies.Accepted.P6f7d25984ff8.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 4 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 4 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 5 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 5 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 6 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 6 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 7 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 7 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 8 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 8 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 9 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 9 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 10 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 10 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 11 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 11 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 12 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 12 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 13 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 13 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 14 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 14 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 15 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 15 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseProduct ∧ k = 16 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else if mode = .PhaseTripleProduct ∧ k = 16 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatedPoints
      mode k
  else
    baselineGeneratedPoints mode k

def bestKnownGeneratePointsInOrder
    (mode : ProductMode) (k : Nat) (hk : k >= 2) : List Point :=
  if mode = .PhaseProduct ∧ k = 2 then
    Policies.Accepted.P6f7d25984ff8.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 2 then
    Policies.Accepted.P52ec6fce9b57.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 3 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 3 then
    Policies.Accepted.P6f7d25984ff8.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 4 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 4 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 5 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 5 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 6 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 6 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 7 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 7 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 8 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 8 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 9 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 9 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 10 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 10 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 11 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 11 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 12 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 12 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 13 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 13 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 14 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 14 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 15 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 15 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseProduct ∧ k = 16 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 16 then
    Policies.Accepted.Pf4aff955f16b.implementation.generatePointsInOrder
      mode k hk
  else
    baselineGeneratePointsInOrder mode k hk

def bestKnownGenerate
    (mode : ProductMode) (k : Nat) (hk : k >= 2) : Prog k :=
  if mode = .PhaseProduct ∧ k = 2 then
    Policies.Accepted.P6f7d25984ff8.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 2 then
    Policies.Accepted.P52ec6fce9b57.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 3 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 3 then
    Policies.Accepted.P6f7d25984ff8.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 4 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 4 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 5 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 5 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 6 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 6 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 7 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 7 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 8 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 8 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 9 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 9 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 10 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 10 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 11 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 11 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 12 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 12 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 13 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 13 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 14 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 14 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 15 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 15 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseProduct ∧ k = 16 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else if mode = .PhaseTripleProduct ∧ k = 16 then
    Policies.Accepted.Pf4aff955f16b.implementation.generate
      mode k hk
  else
    baselineGenerate mode k hk

def bestKnownPolicyId (mode : ProductMode) (k : Nat) : String :=
  if mode = .PhaseProduct ∧ k = 2 then
    "6f7d25984ff8f4db772a7449c097a6e16098f8be"
  else if mode = .PhaseTripleProduct ∧ k = 2 then
    "52ec6fce9b57cf5a3b2b3ed34b6d1e61f6cbaade"
  else if mode = .PhaseProduct ∧ k = 3 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 3 then
    "6f7d25984ff8f4db772a7449c097a6e16098f8be"
  else if mode = .PhaseProduct ∧ k = 4 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 4 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseProduct ∧ k = 5 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 5 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseProduct ∧ k = 6 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 6 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseProduct ∧ k = 7 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 7 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseProduct ∧ k = 8 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 8 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseProduct ∧ k = 9 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 9 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseProduct ∧ k = 10 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 10 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseProduct ∧ k = 11 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 11 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseProduct ∧ k = 12 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 12 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseProduct ∧ k = 13 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 13 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseProduct ∧ k = 14 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 14 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseProduct ∧ k = 15 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 15 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseProduct ∧ k = 16 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else if mode = .PhaseTripleProduct ∧ k = 16 then
    "f4aff955f16b6cb82982e2550b34ebc29c6992b1"
  else
    "general"

end TableGeneration
